# Generated by Django 5.2.9 on 2025-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
