# Generated by Django 5.2.9 on 2025-12-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usermaster_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
