# Generated by Django 5.2.9 on 2025-12-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_usermaster_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermaster',
            old_name='is_verfied',
            new_name='is_verified',
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
