# Generated by Django 5.2.9 on 2025-12-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_is_verfied_usermaster_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(null=True),
        ),
    ]
