# Generated by Django 5.2.9 on 2025-12-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_candidate_max_salary_candidate_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='highestedu',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_type',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobcategory',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='jobdescription',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='candidate',
            name='shift',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='candidate',
            name='website',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='max_salary',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='min_salary',
            field=models.BigIntegerField(default=0),
        ),
    ]
