# Generated by Django 5.2.9 on 2025-12-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_candidate_country_candidate_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='highestedu',
            new_name='highest_education',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='jobcategory',
            new_name='job_category',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='jobdescription',
            new_name='job_description',
        ),
    ]
