# Generated by Django 5.2.9 on 2025-12-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_highestedu_candidate_highest_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
