# Generated by Django 5.2.9 on 2025-12-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_candidate_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='job_description',
            new_name='profile_summary',
        ),
    ]
