# Generated by Django 5.2.9 on 2025-12-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_job_description_candidate_profile_summary'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermaster',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usermaster',
            name='username',
        ),
    ]
