# Generated by Django 5.2.9 on 2025-12-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_usermaster_managers_remove_usermaster_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
