# Generated by Django 5.2.9 on 2025-12-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_company_address_alter_company_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
