# Generated by Django 5.2.9 on 2025-12-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_company_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=250)),
                ('company_address', models.CharField(max_length=250)),
                ('job_description', models.TextField(max_length=500)),
                ('qualification', models.CharField(max_length=250)),
                ('responsibility', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('company_website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('salary_package', models.CharField(max_length=250)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='company_address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='website',
            new_name='company_website',
        ),
    ]
