# Generated by Django 5.2.9 on 2025-12-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_jobdetails_rename_address_company_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='contact',
            new_name='company_contact',
        ),
    ]
