# Generated by Django 5.2.9 on 2026-01-05 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_contact_company_company_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='responsibility',
            new_name='responsibilities',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='jobpost'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
