# Generated by Django 5.2.9 on 2026-01-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_responsibility_jobdetails_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
