# Generated by Django 5.2.9 on 2026-01-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
