# Generated by Django 5.2.9 on 2026-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
