# Generated by Django 5.2.9 on 2026-01-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_jobdetails_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
