# Generated by Django 5.2.9 on 2026-01-05 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_usermaster_is_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('min_salary', models.CharField(max_length=200)),
                ('max_salary', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='resume')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jobdetails')),
            ],
        ),
    ]
