# Generated by Django 5.2.9 on 2026-01-05 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_applyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 5, 19, 14, 7, 825182, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
