# Generated by Django 5.2.9 on 2026-01-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_jobdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
