# Generated by Django 5.2.9 on 2026-01-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_jobdetails_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote')], default='full_time', max_length=200),
        ),
    ]
