# Generated by Django 5.2.9 on 2026-01-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_jobdetails_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
