# Generated by Django 5.2.9 on 2026-01-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_jobdetails_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='logo',
        ),
    ]
