# Generated by Django 5.2.9 on 2026-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_jobdetails_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='company',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='jobpost'),
        ),
    ]
