# Generated by Django 5.2.9 on 2026-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_jobdetails_company_jobdetails_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_category',
            field=models.CharField(choices=[('technology & IT', 'Technology & IT'), ('software development', 'Software Development'), ('data & analytics', 'Data & Analytics'), ('UI / UX & design', 'UI / UX & Design'), ('acounting & finance', 'Accounting & Finance'), ('sales & marketing', 'Sales & Marketing'), ('human resources', 'Human Resources'), ('customer support', 'Customer Support')], default='software development', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('remote', 'Remote')], default='full time', max_length=200),
        ),
    ]
