# Generated by Django 5.2.9 on 2026-01-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_jobdetails_job_category_alter_jobdetails_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_category',
            field=models.CharField(choices=[('technology_&_IT', 'Technology & IT'), ('software_development', 'Software Development'), ('data_&_analytics', 'Data & Analytics'), ('UX_&_design', 'UI / UX & Design'), ('acounting_&_finance', 'Accounting & Finance'), ('sales_&_marketing', 'Sales & Marketing'), ('human_resources', 'Human Resources'), ('customer_support', 'Customer Support')], default='software development', max_length=200),
        ),
    ]
