# Generated by Django 5.2.9 on 2026-01-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_jobdetails_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_category',
            field=models.CharField(choices=[('technology_it', 'Technology & IT'), ('software_development', 'Software Development'), ('data_analytics', 'Data & Analytics'), ('ux_design', 'UI / UX & Design'), ('accounting_finance', 'Accounting & Finance'), ('sales_marketing', 'Sales & Marketing'), ('human_resources', 'Human Resources'), ('customer_support', 'Customer Support')], default='software_development', max_length=200),
        ),
    ]
