# Generated by Django 5.2.9 on 2026-01-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_candidate_user_id_alter_company_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
