# Generated by Django 5.2.9 on 2026-01-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_candidate_user_id_alter_company_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applyjob',
            unique_together={('candidate', 'job')},
        ),
    ]
