# Generated by Django 5.2.9 on 2026-01-18 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_applyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 1, 18, 7, 57, 30, 414106, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
