# Generated by Django 5.2.9 on 2026-01-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_applyjob_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
